<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProdutoSeeder extends Seeder
{
    public function run(): void
    {
        $jogos = [
            [
                'nome' => 'Death Stranding 2: On The Beach',
                'slug' => 'death-stranding-2-on-the-beach',
                'descricao' => 'Do lendário criador de jogos Hideo Kojima vem uma evolução emocionante...',
                'desenvolvedor' => 'Kojima Productions',
                'publisher' => 'Sony Interactive Entertainment',
                'genero' => 'Ação / Aventura',
                'imagem_principal' => 'deathstran2.webp',
                'galeria' => ['death-stranding-2-1.jpg', 'death-stranding-2-2.jpg', 'death-stranding-2-3.jpg'],
                'plataformas' => ['PlayStation 5', 'PlayStation 4', 'PC'],
                'edicoes' => [
                    ['nome' => 'Standard', 'preco' => 350.00],
                    ['nome' => 'Deluxe', 'preco' => 449.90],
                    ['nome' => 'Collector', 'preco' => 699.90],
                ],
                'requisitos' => [
                    'minimo' => [
                        'SO' => 'Windows 10 64-bit',
                        'Processador' => 'Intel Core i7-8700',
                        'Memória' => '16 GB RAM',
                        'Armazenamento' => '100 GB',
                    ],
                    'recomendado' => [
                        'SO' => 'Windows 11 64-bit',
                        'Processador' => 'Intel Core i9-12900K',
                        'Memória' => '32 GB RAM',
                        'Armazenamento' => '100 GB SSD',
                    ],
                ],
            ],
            [
                'nome' => 'Silent Hill f',
                'slug' => 'silent-hill-f',
                'descricao' => 'Novo capítulo da famosa franquia de terror.',
                'desenvolvedor' => 'Neobards Entertainment',
                'publisher' => 'Konami',
                'genero' => 'Terror',
                'imagem_principal' => 'sillenthillF.webp',
                'galeria' => [],
                'plataformas' => ['PS5', 'PC'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 249.90]],
                'requisitos' => null,
            ],
            [
                'nome' => 'Expedição 33',
                'slug' => 'expedicao-33',
                'descricao' => 'Aventura épica em mundos desconhecidos.',
                'desenvolvedor' => 'Sandfall Interactive',
                'publisher' => 'Kepler Interactive',
                'genero' => 'RPG',
                'imagem_principal' => 'exped33.webp',
                'galeria' => [],
                'plataformas' => ['Xbox', 'PC'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 199.90]],
                'requisitos' => null,
            ],
            [
                'nome' => 'Ghost of Yotei',
                'slug' => 'ghost-of-yotei',
                'descricao' => 'Espiritual sucessor de Ghost of Tsushima.',
                'desenvolvedor' => 'Sucker Punch',
                'publisher' => 'Sony',
                'genero' => 'Ação',
                'imagem_principal' => 'ghost.webp',
                'galeria' => [],
                'plataformas' => ['PS5'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 349.90]],
                'requisitos' => null,
            ],
            [
                'nome' => 'Resident Evil 9',
                'slug' => 'resident-evil-9',
                'descricao' => 'Novo título da franquia de horror.',
                'desenvolvedor' => 'Capcom',
                'publisher' => 'Capcom',
                'genero' => 'Terror',
                'imagem_principal' => 'resevil.webp',
                'galeria' => [],
                'plataformas' => ['PS5', 'Xbox', 'PC'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 279.90]],
                'requisitos' => null,
            ],
            [
                'nome' => 'God of War Ragnarök',
                'slug' => 'god-of-war-ragnarok',
                'descricao' => 'A continuação da saga nórdica.',
                'desenvolvedor' => 'Santa Monica Studio',
                'publisher' => 'Sony',
                'genero' => 'Ação',
                'imagem_principal' => 'gow.webp',
                'galeria' => [],
                'plataformas' => ['PS5', 'PS4'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 299.90]],
                'requisitos' => null,
            ],
            [
                'nome' => 'The Last of Us Part III',
                'slug' => 'the-last-of-us-part-iii',
                'descricao' => 'Novo capítulo da história.',
                'desenvolvedor' => 'Naughty Dog',
                'publisher' => 'Sony',
                'genero' => 'Aventura',
                'imagem_principal' => 'tlou.webp',
                'galeria' => [],
                'plataformas' => ['PS5'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 349.90]],
                'requisitos' => null,
            ],
            [
                'nome' => 'Hunt: Showdown 1896',
                'slug' => 'hunt-showdown-1896',
                'descricao' => 'Caça a monstros no velho oeste.',
                'desenvolvedor' => 'Crytek',
                'publisher' => 'Crytek',
                'genero' => 'Tiro, Terror',
                'imagem_principal' => 'hunt.webp',
                'galeria' => [],
                'plataformas' => ['PC', 'Xbox', 'PS5'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 159.90]],
                'requisitos' => null,
            ],
            [
                'nome' => 'Hogwarts Legacy 2',
                'slug' => 'hogwarts-legacy-2',
                'descricao' => 'Volte a Hogwarts em nova aventura.',
                'desenvolvedor' => 'Avalanche Software',
                'publisher' => 'Warner Bros',
                'genero' => 'RPG',
                'imagem_principal' => 'hogleg.webp',
                'galeria' => [],
                'plataformas' => ['PC', 'PS5', 'Xbox'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 299.90]],
                'requisitos' => null,
            ],
            [
                'nome' => 'Pokémon Legends Z-A',
                'slug' => 'pokemon-legends-za',
                'descricao' => 'Nova aventura no mundo Pokémon.',
                'desenvolvedor' => 'Game Freak',
                'publisher' => 'Nintendo',
                'genero' => 'RPG',
                'imagem_principal' => 'pokemon.webp',
                'galeria' => [],
                'plataformas' => ['Nintendo Switch'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 299.90]],
                'requisitos' => null,
            ],
            [
                'nome' => 'Super Mario Odyssey 2',
                'slug' => 'super-mario-odyssey-2',
                'descricao' => 'Mais aventuras com Mario.',
                'desenvolvedor' => 'Nintendo EPD',
                'publisher' => 'Nintendo',
                'genero' => 'Plataforma',
                'imagem_principal' => 'mario.webp',
                'galeria' => [],
                'plataformas' => ['Nintendo Switch'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 299.90]],
                'requisitos' => null,
            ],
            [
                'nome' => 'The Legend of Zelda: Echoes of Wisdom',
                'slug' => 'zelda-echoes-of-wisdom',
                'descricao' => 'Nova jornada no reino de Hyrule.',
                'desenvolvedor' => 'Nintendo',
                'publisher' => 'Nintendo',
                'genero' => 'Aventura',
                'imagem_principal' => 'zelda.webp',
                'galeria' => [],
                'plataformas' => ['Nintendo Switch'],
                'edicoes' => [['nome' => 'Standard', 'preco' => 299.90]],
                'requisitos' => null,
            ],
        ];

        foreach ($jogos as $jogo) {
            DB::table('produtos')->insert([
                'nome' => $jogo['nome'],
                'slug' => $jogo['slug'],
                'descricao' => $jogo['descricao'],
                'desenvolvedor' => $jogo['desenvolvedor'],
                'publisher' => $jogo['publisher'],
                'genero' => $jogo['genero'],
                'imagem_principal' => $jogo['imagem_principal'],
                'galeria' => json_encode($jogo['galeria']),
                'plataformas' => json_encode($jogo['plataformas']),
                'edicoes' => json_encode($jogo['edicoes']),
                'requisitos' => $jogo['requisitos'] ? json_encode($jogo['requisitos']) : null,
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}